# Generated by Django 5.0.6 on 2025-08-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_discount_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Название, напр. НДС', max_length=50)),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Процент, напр. 20.00', max_digits=5)),
                ('inclusive', models.BooleanField(default=False, help_text='Включён в цену (True) или сверху (False)')),
                ('active', models.BooleanField(default=True)),
                ('stripe_tax_rate_id', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='orders', to='catalog.tax'),
        ),
    ]
